#!/bin/bash
# Desc: moonth_move helper for Stellarium
# Requires: apt install jq bc wget
# Requires: Stellarium plugin enabled: Remote Control

set +x
if [ "x$1" == "x" ]; then
  echo "moonth_move requires a positive or negative integer as an argument."
  exit 0
fi

ADD=$1
IP=127.0.0.1

CUR=$(wget -O - -q http://$IP:8090/api/main/status | jq '.time.jday')
MONTH_DAYS=$( echo " ${ADD} * 29.5306 " | bc -l )
MONTH_DAYS=$( printf "%.0f" $MONTH_DAYS ) # round
DT=$( echo " ${CUR} + ${MONTH_DAYS} " | bc -l )
echo $DT
echo $CUR
wget -O - -q --post-data="time=${DT}" http://$IP:8090/api/main/time
